### PR TITLE
improve PreTransformIndex

### PR DESCRIPTION
**Pull request by ava57r**

### CODE REVIEW

**Comment by ava57r** [comment]
faiss PR https://github.com/facebookresearch/faiss/pull/1945

**Comment by ava57r** [comment]
#33

**Review by Enet4 — COMMENTED** [review]
Looks OK to me, but like in #58, I would greatly appreciate some documentation

**Comment by ava57r** [comment]
the faiss method has not any a documentation.
https://github.com/facebookresearch/faiss/blob/main/faiss/IndexPreTransform.h#L38

I did find an example with the method.
I did not catch a main idea.

**Pull request merged**
