### PR TITLE
x86 compatibility

### PR DESCRIPTION
**Pull request by guskovd**
faiss-rs does not work on the x86 platform. This fix allows you to build faiss-rs on x86 and x86_64 platforms

### CODE REVIEW

**Comment by guskovd** [comment]
* My edits are aimed only at library building. 
* I tried using isize. Got a lot of the same errors:

```bash
I tried using isizeerror[E0308]: mismatched types
   --> src/macros.rs:38:66
    |
38  |                     faiss_try!(faiss_Index_add(self.inner_ptr(), n as isize, x.as_ptr()));
    |                                                                  ^^^^^^^^^^ expected `i64`, found `isize`
    | 
   ::: src/index/flat.rs:128:1
    |
128 | impl_native_index!(FlatIndex);
    | ------------------------------ in this macro invocation
    |
help: you can convert an `isize` to `i64` and panic if the converted value wouldn't fit
    |
38  |                     faiss_try!(faiss_Index_add(self.inner_ptr(), (n as isize).try_into().unwrap(), x.as_ptr()));
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by guskovd** [comment]
The library is dependent on our project, which needs to be built on the x86 and x64 platforms. I already realized that these edits will not make work with libfaiss_c.so (simply because it is not going to x86)
---
I think the library should be built anyway, whether it is used or not

**Comment by Enet4** [comment]
Sorry, but I'm at a loss here. The C API unequivocally defines the idx type to `int64_t` (at [faiss_c.h](https://github.com/facebookresearch/faiss/blob/master/c_api/faiss_c.h#L18)). Without access and agreement to the C API, this crate cannot function and should indeed not build successfully.

In the event that you have this crate as a dependency and would like to only actually use it on certain platforms, you can make it a [platform specific dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies).

**Comment by guskovd** [comment]
I think you're right

**Pull request closed without merging**
