### PR TITLE
Add TryFromInnerPtr trait

### PR DESCRIPTION
**Pull request by ava57r**

### CODE REVIEW

**Review by Enet4 — APPROVED** [review]
I suppose we can go with this, although `TryFrom` and `TryInto` are stable now, and I probably would have gone with implementing `From<*mut FaissIndex>` instead of creating `FromInnerPtr` with a bit of extra foresight. Maybe we can leave that to a future reiteration of the high level API.

**Comment by Enet4** [comment]
I think it's high time we have a new version of faiss-rs! I will proceed with `faiss-sys` 0.5.0 and `faiss` 0.10.0 shortly.

@ava57r thank you very much for the continued support on the faiss-rs bindings. I would like to include you as a collaborator of the project. This is not with the intention to delegate extra work or burden to you (even seeing this as a low traffic project), nor to change the cycle of contribution, but to give you and other users additional confidence in the project's maintenance.

**Comment by ava57r** [comment]
First I tried to use `TryFrom` `IdMap<A>` to `IdMap<B>`.
It does not work.
like 
`conflict impl with std library`

**Comment by ava57r** [comment]
I tried this code 

```rust
impl<A, B> TryFrom<IdMap<A>> for IdMap<B>
where 
    A: NativeIndex,
    B: index::TryFromInnerPtr,
{
    type Error = Error;
    fn try_from(value: IdMap<A>) -> ::std::result::Result<Self, Self::Error> {
        todo!()
    }
}
```

```log
conflicting implementations of trait `std::convert::TryFrom<index::id_map::IdMap<_>>` for type `index::id_map::IdMap<_>`
conflicting implementation in crate `core`:
- impl<T, U> TryFrom<U> for T
  where U: Into<T>
```

compiler error https://doc.rust-lang.org/error-index.html#E0119

**Pull request merged**
