### PR TITLE
[faiss v1.7.1] Add Index scalar quantizer

### PR DESCRIPTION
**Pull request by ava57r**
bindings.rs by not released faiss API

### CODE REVIEW

**Comment by ava57r** [comment]
PR merged https://github.com/facebookresearch/faiss/pull/1802

**Comment by ava57r** [comment]
PR https://github.com/facebookresearch/faiss/pull/1829 merged

**Comment by Enet4** [comment]
Hello @ava57r. When you have the time, could you please rebase these pull requests? I brought back CI and would like to have these checked through it.

**Comment by ava57r** [comment]
I finished rebase.

**Review by Enet4 — COMMENTED** [review]
Minor nit, but should be good to enter afterwards.

**Review by Enet4 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
